# top level

# Currently only checks functiosn
# required means must have elements
# optional means can have elements
# multi means duplicates allowed (require at least one)

pipeline:
  required:
    - agent
    - stages # once
  optional:
    - parameters
    - options
    - triggers
    - post
    - environment
    - tools


agent:
  args:
    - any
    - none

stages:
  multi:
    - stage

# a bit complicated mhmm
parallel:
  multi:
    - stage


stage:
  required:
    - steps
  optional:
    - agent
    - post
    - environment
    - tools
    - options
    - when

# directives
parameters:
  multi:
    - string
    - booleanParam

triggers:
  # only one allowed?
  optional:
    - cron
    - pollSCM
    - upstream
